"use client";

import { DATA } from "@/data/resume";
import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import { SectionHead, rise } from "./ui";

/* ------------------------------------------------------------------ *
 *  The GitHub profile banner, re-themed with the landing tokens
 *  (generated by the profile repo's `assests/generator`, not by hand).
 *  Two files: the full 1180×610 banner for large screens, and the
 *  portrait card alone for phones/tablets where 9px characters would
 *  be unreadable. The SVG animates with SMIL only — no JavaScript.
 * ------------------------------------------------------------------ */
export function Profile({ compact = false }: { compact?: boolean }) {
  const github = DATA.contact.social.GitHub.url;
  return (
    <section id="profile" className="scroll-mt-24">
      {/* `compact` drops the heading: used when the banner is the first block on the page,
          where a section title above the real headline would read as a page title. */}
      {!compact && (
        <SectionHead
          eyebrow="system.info"
          title="The profile, as a terminal"
          blurb="The identity card that sits on my GitHub profile — portrait rendered in characters, roles, stack and selected work."
        />
      )}
      <motion.div
        {...rise}
        className="overflow-hidden rounded-2xl border border-landing-line/10 bg-landing-surface p-2 sm:p-3"
      >
        <picture>
          <source media="(min-width: 1024px)" srcSet="/profile-banner.svg" />
          {/* eslint-disable-next-line @next/next/no-img-element -- <picture> media switching needs a plain img */}
          <img
            src="/profile-banner-mobile.svg"
            alt={`${DATA.name} — terminal-style profile card with a character-rendered portrait`}
            loading="lazy"
            className="mx-auto block h-auto w-full max-w-[460px] rounded-xl lg:max-w-none"
          />
        </picture>
      </motion.div>
      <motion.p
        {...rise}
        transition={{ ...rise.transition, delay: 0.05 }}
        className="mt-3 font-mono text-[11px] text-landing-dim"
      >
        Rendered from the same card on{" "}
        <a
          href={github}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-0.5 text-landing-accent hover:underline"
        >
          github.com/sushantkr961 <ArrowUpRight className="size-3" />
        </a>{" "}
        · SVG + SMIL, no JavaScript
      </motion.p>
    </section>
  );
}
