"use client";

/* Desktop + iPad wallpaper: the terminal banner rendered as a full-bleed 1920x1200 SVG
   (generated by the profile repo's generator, `--card wallpaper`). The iPhone layout keeps
   /wallpaper.jpg on purpose — a wide banner cover-cropped to a portrait phone is noise. */
export function Wallpaper() {
  return (
    <div className="absolute inset-0 overflow-hidden">
      <img
        src="/profile-wallpaper.svg"
        alt=""
        className="absolute inset-0 w-full h-full object-cover"
        draggable={false}
      />
    </div>
  );
}
